image: "node:12-alpine"

stages: 
  - release

variables:
  PLUGIN_NAME: 'koha-plugin-slnp-ill'
  PLUGIN_EXTENSION: 'kpz'

build: 
  stage: release
  script:
    - apk add --update zip curl jq git
    - npm install
    - npm install -g gulp-cli
    - gulp build
    - "UPLOAD_URL=$(curl --request POST --header \"PRIVATE-TOKEN: $PRIVATE_TOKEN\" --form \"file=@$(npm run kpz -s)\" $CI_API_V4_URL/projects/$CI_PROJECT_ID/uploads | jq -r \".url\" )"
    - "curl --header \"Content-Type: application/json\" --header \"PRIVATE-TOKEN: $PRIVATE_TOKEN\" --data \"{ \\\"name\\\": \\\"$(npm run name -s)\\\", \\\"tag_name\\\": \\\"$CI_COMMIT_TAG\\\", \\\"description\\\":  \\\"release $CI_COMMIT_TAG\\\", \\\"assets\\\": { \\\"links\\\": [{ \\\"name\\\": \\\"$(npm run name -s)\\\", \\\"url\\\": \\\"$CI_PROJECT_URL$UPLOAD_URL\\\" }] } }\" --request POST $CI_API_V4_URL/projects/$CI_PROJECT_ID/releases"
    - "curl --header \"JOB-TOKEN: $CI_JOB_TOKEN\" --upload-file ${PLUGIN_NAME}-${CI_COMMIT_TAG}.${PLUGIN_EXTENSION} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PLUGIN_NAME}/${CI_COMMIT_TAG}/${PLUGIN_NAME}-${CI_COMMIT_TAG}.${PLUGIN_EXTENSION}"

  only:
    - tags
